export const baseConfig = {
  toolbar: [
    'history',
    'textStyle',
    'fontSize',
    'bold',
    'italic',
    'underline',
    'codeBlock',
    'fontColor',
    'bgColor',
    'textFormatting',
    'contents',
    'textAlign',
  ],
  textStyle: [
    'nomarl',
    'headisng1',
    'heading2',
    'heading3',
    'bulletList',
    'numberList',
    'checkList',
    'quote',
    'codeBlock',
  ],
  fonts: [],
  fontSize: {
    min: 8,
    max: 70,
  },
  textFormatting: [
    'lowercase',
    'uppercase',
    'capitalize',
    'strikethrough',
    'subscript',
    'superscript',
    'clearFormatting',
  ],
  contents: [
    'horizontalRule',
    'pageBreak',
    'image',
    'inlineImage',
    'gif',
    'table',
    'columnLayout',
    'collapsible',
    'youtube',
  ],
};
