default:
  tags:
    - docker

stages:
  # - build
  - deploy

# pnpm 관련 캐시 설정
# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - .pnpm-store
#     - node_modules/
#     - apps/*/node_modules
#     - libs/*/node_modules

# build:
#   stage: build
#   image: node:18
#   before_script:
#     #
#     - npm config set strict-ssl false
#     #pnpm 설치
#     - npm install -g pnpm
#     - npm install -g nx
#     - pnpm config set store-dir .pnpm-store
#   script:
#     - pnpm install --no-frozen-lockfile
#     - npx nx build fo
#     # - npx nx build bo
#   artifacts:
#     paths:
#       - dist/apps/fo
#       # - dist/apps/bo
#   only:
#     - main
#### S3 업로드 권한 요청 중
deploy:
  stage: deploy
  image: amazon/aws-cli:latest
  # dependencies: # build 단계의 artifacts 를 사용.
  #   - build
  script:
    - echo "AWS CLI Version:"
    - aws --version
    - echo "Listing S3 Buckets..."
    - aws s3 ls
    - echo "Syncing to S3..."
    - aws s3 sync dist/apps/fo s3://hmgnlp-dev-front-web/fo --delete
  only:
    - main
  variables:
    AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID_DEV}'
    AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY_DEV}'
    AWS_DEFAULT_REGION: 'ap-northeast-2'
