import type { EditorThemeClasses } from 'lexical';

import '../assets/styles/editor.css';

const themeConfig: EditorThemeClasses = {
  autocomplete: 'nlp--editor-autocomplete',
  blockCursor: 'nlp--editor-block-cursor',
  characterLimit: 'nlp--editor-character-limit',
  code: 'nlp--editor-code',
  codeHighlight: {
    atrule: 'nlp--editor-token-attr',
    attr: 'nlp--editor-token-attr',
    boolean: 'nlp--editor-token-property',
    builtin: 'nlp--editor-token-selector',
    cdata: 'nlp--editor-token-comment',
    char: 'nlp--editor-token-selector',
    class: 'nlp--editor-token-function',
    'class-name': 'nlp--editor-token-function',
    comment: 'nlp--editor-token-comment',
    constant: 'nlp--editor-token-property',
    deleted: 'nlp--editor-token-property',
    doctype: 'nlp--editor-token-comment',
    entity: 'nlp--editor-token-operator',
    function: 'nlp--editor-token-function',
    important: 'nlp--editor-token-variable',
    inserted: 'nlp--editor-token-selector',
    keyword: 'nlp--editor-token-attr',
    namespace: 'nlp--editor-token-variable',
    number: 'nlp--editor-token-property',
    operator: 'nlp--editor-token-operator',
    prolog: 'nlp--editor-token-comment',
    property: 'nlp--editor-token-property',
    punctuation: 'nlp--editor-token-punctuation',
    regex: 'nlp--editor-token-variable',
    selector: 'nlp--editor-token-selector',
    string: 'nlp--editor-token-selector',
    symbol: 'nlp--editor-token-property',
    tag: 'nlp--editor-token-property',
    url: 'nlp--editor-token-operator',
    variable: 'nlp--editor-token-variable',
  },
  embedBlock: {
    base: 'nlp--editor-embed-block',
    focus: 'nlp--editor-embed-block-focus',
  },
  hashtag: 'nlp--editor-hashtag',
  heading: {
    h1: 'nlp--editor-h1',
    h2: 'nlp--editor-h2',
    h3: 'nlp--editor-h3',
    h4: 'nlp--editor-h4',
    h5: 'nlp--editor-h5',
    h6: 'nlp--editor-h6',
  },
  hr: 'nlp--editor-hr',
  image: 'editor-image',
  indent: 'nlp--editor-indent',
  inlineImage: 'inline-editor-image',
  layoutContainer: 'nlp--editor-layout-container',
  layoutItem: 'nlp--editor-layout-item',
  link: 'nlp--editor-link',
  list: {
    checklist: 'nlp--editor-checklist',
    listitem: 'nlp--editor-list-item',
    listitemChecked: 'nlp--editor-list-item-checked',
    listitemUnchecked: 'nlp--editor-list-item-unchecked',
    nested: {
      listitem: 'nlp--editor-nested-list-item',
    },
    olDepth: [
      'nlp--editor-ol1',
      'nlp--editor-ol2',
      'nlp--editor-ol3',
      'nlp--editor-ol4',
      'nlp--editor-ol5',
    ],
    ul: 'nlp--editor-ul',
  },
  ltr: 'nlp--editor-ltr',
  mark: 'nlp--editor-mark',
  markOverlap: 'nlp--editor-mark-overlap',
  paragraph: 'nlp--editor-paragraph',
  quote: 'nlp--editor-quote',
  rtl: 'nlp--editor-rtl',
  specialText: 'nlp--editor-special-text',
  tab: 'nlp--editor-tab-node',
  table: 'nlp--editor-table',
  tableCell: 'nlp--editor-table-cell',
  tableCellActionButton: 'nlp--editor-table-cell-action-button',
  tableCellActionButtonContainer: 'nlp--editor-table-cell-action-button-container',
  tableCellHeader: 'nlp--editor-table-cell-header',
  tableCellResizer: 'nlp--editor-table-cell-resizer',
  tableCellSelected: 'nlp--editor-table-cell-selected',
  tableRowStriping: 'nlp--editor-table-row-striping',
  tableScrollableWrapper: 'nlp--editor-table-scrollable-wrapper',
  tableSelected: 'nlp--editor-table-selected',
  tableSelection: 'nlp--editor-table-selection',
  text: {
    bold: 'nlp--editor-text-bold',
    capitalize: 'nlp--editor-text-capitalize',
    code: 'nlp--editor-text-code',
    italic: 'nlp--editor-text-italic',
    lowercase: 'nlp--editor-text-lowercase',
    strikethrough: 'nlp--editor-text-strikethrough',
    subscript: 'nlp--editor-text-subscript',
    superscript: 'nlp--editor-text-superscript',
    underline: 'nlp--editor-text-underline',
    underlineStrikethrough: 'nlp--editor-text-under-line-strikethrough',
    uppercase: 'nlp--editor-text-uppercase',
  },
};

export default themeConfig;
