/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as TestImport } from './pages/test'
import { Route as LayoutImport } from './pages/_layout'
import { Route as LoginIndexImport } from './pages/login/index'
import { Route as LayoutIndexImport } from './pages/_layout/index'
import { Route as LayoutMenuIndexImport } from './pages/_layout/menu/index'
import { Route as LayoutMenuMenuIdImport } from './pages/_layout/menu/$menuId'
import { Route as LayoutAppleRouteImport } from './pages/_layout/apple/_route'

// Create Virtual Routes

const LayoutAppleImport = createFileRoute('/_layout/apple')()

// Create/Update Routes

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutAppleRoute = LayoutAppleImport.update({
  id: '/apple',
  path: '/apple',
  getParentRoute: () => LayoutRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMenuIndexRoute = LayoutMenuIndexImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMenuMenuIdRoute = LayoutMenuMenuIdImport.update({
  id: '/menu/$menuId',
  path: '/menu/$menuId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAppleRouteRoute = LayoutAppleRouteImport.update({
  id: '/_route',
  getParentRoute: () => LayoutAppleRoute,
} as any).lazy(() =>
  import('./pages/_layout/apple/_route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout/apple': {
      id: '/_layout/apple'
      path: '/apple'
      fullPath: '/apple'
      preLoaderRoute: typeof LayoutAppleImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/apple/_route': {
      id: '/_layout/apple/_route'
      path: '/apple'
      fullPath: '/apple'
      preLoaderRoute: typeof LayoutAppleRouteImport
      parentRoute: typeof LayoutAppleRoute
    }
    '/_layout/menu/$menuId': {
      id: '/_layout/menu/$menuId'
      path: '/menu/$menuId'
      fullPath: '/menu/$menuId'
      preLoaderRoute: typeof LayoutMenuMenuIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/menu/': {
      id: '/_layout/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof LayoutMenuIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutAppleRouteChildren {
  LayoutAppleRouteRoute: typeof LayoutAppleRouteRoute
}

const LayoutAppleRouteChildren: LayoutAppleRouteChildren = {
  LayoutAppleRouteRoute: LayoutAppleRouteRoute,
}

const LayoutAppleRouteWithChildren = LayoutAppleRoute._addFileChildren(
  LayoutAppleRouteChildren,
)

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAppleRoute: typeof LayoutAppleRouteWithChildren
  LayoutMenuMenuIdRoute: typeof LayoutMenuMenuIdRoute
  LayoutMenuIndexRoute: typeof LayoutMenuIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAppleRoute: LayoutAppleRouteWithChildren,
  LayoutMenuMenuIdRoute: LayoutMenuMenuIdRoute,
  LayoutMenuIndexRoute: LayoutMenuIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/test': typeof TestRoute
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/apple': typeof LayoutAppleRouteRoute
  '/menu/$menuId': typeof LayoutMenuMenuIdRoute
  '/menu': typeof LayoutMenuIndexRoute
}

export interface FileRoutesByTo {
  '/test': typeof TestRoute
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/apple': typeof LayoutAppleRouteRoute
  '/menu/$menuId': typeof LayoutMenuMenuIdRoute
  '/menu': typeof LayoutMenuIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/test': typeof TestRoute
  '/_layout/': typeof LayoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_layout/apple': typeof LayoutAppleRouteWithChildren
  '/_layout/apple/_route': typeof LayoutAppleRouteRoute
  '/_layout/menu/$menuId': typeof LayoutMenuMenuIdRoute
  '/_layout/menu/': typeof LayoutMenuIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/test'
    | '/'
    | '/login'
    | '/apple'
    | '/menu/$menuId'
    | '/menu'
  fileRoutesByTo: FileRoutesByTo
  to: '/test' | '/' | '/login' | '/apple' | '/menu/$menuId' | '/menu'
  id:
    | '__root__'
    | '/_layout'
    | '/test'
    | '/_layout/'
    | '/login/'
    | '/_layout/apple'
    | '/_layout/apple/_route'
    | '/_layout/menu/$menuId'
    | '/_layout/menu/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  TestRoute: typeof TestRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  TestRoute: TestRoute,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/test",
        "/login/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/apple",
        "/_layout/menu/$menuId",
        "/_layout/menu/"
      ]
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/_layout/apple": {
      "filePath": "_layout/apple",
      "parent": "/_layout",
      "children": [
        "/_layout/apple/_route"
      ]
    },
    "/_layout/apple/_route": {
      "filePath": "_layout/apple/_route.tsx",
      "parent": "/_layout/apple"
    },
    "/_layout/menu/$menuId": {
      "filePath": "_layout/menu/$menuId.tsx",
      "parent": "/_layout"
    },
    "/_layout/menu/": {
      "filePath": "_layout/menu/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
