/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as TestImport } from './pages/test'
import { Route as LayoutImport } from './pages/_layout'
import { Route as LoginIndexImport } from './pages/login/index'
import { Route as LayoutIndexImport } from './pages/_layout/index'
import { Route as LayoutMenuIndexImport } from './pages/_layout/menu/index'
import { Route as LayoutLearningIndexImport } from './pages/_layout/learning/index'
import { Route as LayoutMenuMenuIdImport } from './pages/_layout/menu/$menuId'
import { Route as LayoutLearningIdVideoImport } from './pages/_layout/learning/$id/video'

// Create/Update Routes

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMenuIndexRoute = LayoutMenuIndexImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLearningIndexRoute = LayoutLearningIndexImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMenuMenuIdRoute = LayoutMenuMenuIdImport.update({
  id: '/menu/$menuId',
  path: '/menu/$menuId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLearningIdVideoRoute = LayoutLearningIdVideoImport.update({
  id: '/learning/$id/video',
  path: '/learning/$id/video',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout/menu/$menuId': {
      id: '/_layout/menu/$menuId'
      path: '/menu/$menuId'
      fullPath: '/menu/$menuId'
      preLoaderRoute: typeof LayoutMenuMenuIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/learning/': {
      id: '/_layout/learning/'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LayoutLearningIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/menu/': {
      id: '/_layout/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof LayoutMenuIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/learning/$id/video': {
      id: '/_layout/learning/$id/video'
      path: '/learning/$id/video'
      fullPath: '/learning/$id/video'
      preLoaderRoute: typeof LayoutLearningIdVideoImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutMenuMenuIdRoute: typeof LayoutMenuMenuIdRoute
  LayoutLearningIndexRoute: typeof LayoutLearningIndexRoute
  LayoutMenuIndexRoute: typeof LayoutMenuIndexRoute
  LayoutLearningIdVideoRoute: typeof LayoutLearningIdVideoRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutMenuMenuIdRoute: LayoutMenuMenuIdRoute,
  LayoutLearningIndexRoute: LayoutLearningIndexRoute,
  LayoutMenuIndexRoute: LayoutMenuIndexRoute,
  LayoutLearningIdVideoRoute: LayoutLearningIdVideoRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/test': typeof TestRoute
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/menu/$menuId': typeof LayoutMenuMenuIdRoute
  '/learning': typeof LayoutLearningIndexRoute
  '/menu': typeof LayoutMenuIndexRoute
  '/learning/$id/video': typeof LayoutLearningIdVideoRoute
}

export interface FileRoutesByTo {
  '/test': typeof TestRoute
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/menu/$menuId': typeof LayoutMenuMenuIdRoute
  '/learning': typeof LayoutLearningIndexRoute
  '/menu': typeof LayoutMenuIndexRoute
  '/learning/$id/video': typeof LayoutLearningIdVideoRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/test': typeof TestRoute
  '/_layout/': typeof LayoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_layout/menu/$menuId': typeof LayoutMenuMenuIdRoute
  '/_layout/learning/': typeof LayoutLearningIndexRoute
  '/_layout/menu/': typeof LayoutMenuIndexRoute
  '/_layout/learning/$id/video': typeof LayoutLearningIdVideoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/test'
    | '/'
    | '/login'
    | '/menu/$menuId'
    | '/learning'
    | '/menu'
    | '/learning/$id/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/test'
    | '/'
    | '/login'
    | '/menu/$menuId'
    | '/learning'
    | '/menu'
    | '/learning/$id/video'
  id:
    | '__root__'
    | '/_layout'
    | '/test'
    | '/_layout/'
    | '/login/'
    | '/_layout/menu/$menuId'
    | '/_layout/learning/'
    | '/_layout/menu/'
    | '/_layout/learning/$id/video'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  TestRoute: typeof TestRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  TestRoute: TestRoute,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/test",
        "/login/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/menu/$menuId",
        "/_layout/learning/",
        "/_layout/menu/",
        "/_layout/learning/$id/video"
      ]
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/_layout/menu/$menuId": {
      "filePath": "_layout/menu/$menuId.tsx",
      "parent": "/_layout"
    },
    "/_layout/learning/": {
      "filePath": "_layout/learning/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/menu/": {
      "filePath": "_layout/menu/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/learning/$id/video": {
      "filePath": "_layout/learning/$id/video.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
