export const CODE_GROUP = {
  LANGUAGE_CODE: 'LANGUAGE_CODE',
  COURSE_CATEGORY: 'COURSE_CATEGORY',
  OPEN_COMPANY_CODE: 'OPEN_COMPANY_CODE',
};
export type CODE_GROUP = (typeof CODE_GROUP)[keyof typeof CODE_GROUP];
