/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './pages/__root';
import { Route as LayoutImport } from './pages/_layout';
import { Route as GuideImport } from './pages/_guide';
import { Route as LoginIndexImport } from './pages/login/index';
import { Route as LayoutIndexImport } from './pages/_layout/index';
import { Route as LoginLayoutImport } from './pages/login/_layout';
import { Route as LayoutMenu3IndexImport } from './pages/_layout/menu3/index';
import { Route as GuideGuideIndexImport } from './pages/_guide/guide/index';
import { Route as LayoutMenu8Menu9Import } from './pages/_layout/menu8/menu9';
import { Route as LayoutMenu4Menu5Import } from './pages/_layout/menu4/menu5';
import { Route as GuideGuideTypographyImport } from './pages/_guide/guide/typography';
import { Route as GuideGuideRespondImport } from './pages/_guide/guide/respond';
import { Route as GuideGuideInfoImport } from './pages/_guide/guide/info';
import { Route as GuideGuideColorImport } from './pages/_guide/guide/color';
import { Route as GuideGuideButtonImport } from './pages/_guide/guide/button';
import { Route as GuideGuideComponentsButtonImport } from './pages/_guide/guide/components/Button';
import { Route as GuideGuideComponentsLayoutImport } from './pages/_guide/guide/components/Layout';

// Create Virtual Routes

const LoginImport = createFileRoute('/login')();

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any);

const GuideRoute = GuideImport.update({
  id: '/_guide',
  getParentRoute: () => rootRoute,
} as any);

const LoginIndexRoute = LoginIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any);

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any);

const LoginLayoutRoute = LoginLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LoginRoute,
} as any);

const LayoutMenu3IndexRoute = LayoutMenu3IndexImport.update({
  id: '/menu3/',
  path: '/menu3/',
  getParentRoute: () => LayoutRoute,
} as any);

const GuideGuideIndexRoute = GuideGuideIndexImport.update({
  id: '/guide/',
  path: '/guide/',
  getParentRoute: () => GuideRoute,
} as any);

const LayoutMenu8Menu9Route = LayoutMenu8Menu9Import.update({
  id: '/menu8/menu9',
  path: '/menu8/menu9',
  getParentRoute: () => LayoutRoute,
} as any);

const LayoutMenu4Menu5Route = LayoutMenu4Menu5Import.update({
  id: '/menu4/menu5',
  path: '/menu4/menu5',
  getParentRoute: () => LayoutRoute,
} as any);

const GuideGuideTypographyRoute = GuideGuideTypographyImport.update({
  id: '/guide/typography',
  path: '/guide/typography',
  getParentRoute: () => GuideRoute,
} as any);

const GuideGuideRespondRoute = GuideGuideRespondImport.update({
  id: '/guide/respond',
  path: '/guide/respond',
  getParentRoute: () => GuideRoute,
} as any);

const GuideGuideInfoRoute = GuideGuideInfoImport.update({
  id: '/guide/info',
  path: '/guide/info',
  getParentRoute: () => GuideRoute,
} as any);

const GuideGuideColorRoute = GuideGuideColorImport.update({
  id: '/guide/color',
  path: '/guide/color',
  getParentRoute: () => GuideRoute,
} as any);

const GuideGuideButtonRoute = GuideGuideButtonImport.update({
  id: '/guide/button',
  path: '/guide/button',
  getParentRoute: () => GuideRoute,
} as any);

const GuideGuideComponentsLuttonRoute = GuideGuideComponentsLuttonImport.update({
  id: '/guide/components/Lutton',
  path: '/guide/components/Lutton',
  getParentRoute: () => GuideRoute,
} as any);

const GuideGuideComponentsLayoutRoute = GuideGuideComponentsLayoutImport.update({
  id: '/guide/components/Layout',
  path: '/guide/components/Layout',
  getParentRoute: () => GuideRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guide': {
      id: '/_guide';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof GuideImport;
      parentRoute: typeof rootRoute;
    };
    '/_layout': {
      id: '/_layout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof LayoutImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/login/_layout': {
      id: '/login/_layout';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginLayoutImport;
      parentRoute: typeof LoginRoute;
    };
    '/_layout/': {
      id: '/_layout/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof LayoutIndexImport;
      parentRoute: typeof LayoutImport;
    };
    '/login/': {
      id: '/login/';
      path: '/';
      fullPath: '/login/';
      preLoaderRoute: typeof LoginIndexImport;
      parentRoute: typeof LoginImport;
    };
    '/_guide/guide/button': {
      id: '/_guide/guide/button';
      path: '/guide/button';
      fullPath: '/guide/button';
      preLoaderRoute: typeof GuideGuideButtonImport;
      parentRoute: typeof GuideImport;
    };
    '/_guide/guide/color': {
      id: '/_guide/guide/color';
      path: '/guide/color';
      fullPath: '/guide/color';
      preLoaderRoute: typeof GuideGuideColorImport;
      parentRoute: typeof GuideImport;
    };
    '/_guide/guide/info': {
      id: '/_guide/guide/info';
      path: '/guide/info';
      fullPath: '/guide/info';
      preLoaderRoute: typeof GuideGuideInfoImport;
      parentRoute: typeof GuideImport;
    };
    '/_guide/guide/respond': {
      id: '/_guide/guide/respond';
      path: '/guide/respond';
      fullPath: '/guide/respond';
      preLoaderRoute: typeof GuideGuideRespondImport;
      parentRoute: typeof GuideImport;
    };
    '/_guide/guide/typography': {
      id: '/_guide/guide/typography';
      path: '/guide/typography';
      fullPath: '/guide/typography';
      preLoaderRoute: typeof GuideGuideTypographyImport;
      parentRoute: typeof GuideImport;
    };
    '/_layout/menu4/menu5': {
      id: '/_layout/menu4/menu5';
      path: '/menu4/menu5';
      fullPath: '/menu4/menu5';
      preLoaderRoute: typeof LayoutMenu4Menu5Import;
      parentRoute: typeof LayoutImport;
    };
    '/_layout/menu8/menu9': {
      id: '/_layout/menu8/menu9';
      path: '/menu8/menu9';
      fullPath: '/menu8/menu9';
      preLoaderRoute: typeof LayoutMenu8Menu9Import;
      parentRoute: typeof LayoutImport;
    };
    '/_guide/guide/': {
      id: '/_guide/guide/';
      path: '/guide';
      fullPath: '/guide';
      preLoaderRoute: typeof GuideGuideIndexImport;
      parentRoute: typeof GuideImport;
    };
    '/_layout/menu3/': {
      id: '/_layout/menu3/';
      path: '/menu3';
      fullPath: '/menu3';
      preLoaderRoute: typeof LayoutMenu3IndexImport;
      parentRoute: typeof LayoutImport;
    };
    '/_guide/guide/components/Layout': {
      id: '/_guide/guide/components/Layout';
      path: '/guide/components/Layout';
      fullPath: '/guide/components/Layout';
      preLoaderRoute: typeof GuideGuideComponentsLayoutImport;
      parentRoute: typeof GuideImport;
    };
    '/_guide/guide/components/Lutton': {
      id: '/_guide/guide/components/Lutton';
      path: '/guide/components/Lutton';
      fullPath: '/guide/components/Lutton';
      preLoaderRoute: typeof GuideGuideComponentsLuttonImport;
      parentRoute: typeof GuideImport;
    };
  }
}

// Create and export the route tree

interface GuideRouteChildren {
  GuideGuideButtonRoute: typeof GuideGuideButtonRoute;
  GuideGuideColorRoute: typeof GuideGuideColorRoute;
  GuideGuideInfoRoute: typeof GuideGuideInfoRoute;
  GuideGuideRespondRoute: typeof GuideGuideRespondRoute;
  GuideGuideTypographyRoute: typeof GuideGuideTypographyRoute;
  GuideGuideIndexRoute: typeof GuideGuideIndexRoute;
  GuideGuideComponentsLayoutRoute: typeof GuideGuideComponentsLayoutRoute;
  GuideGuideComponentsLuttonRoute: typeof GuideGuideComponentsLuttonRoute;
}

const GuideRouteChildren: GuideRouteChildren = {
  GuideGuideButtonRoute: GuideGuideButtonRoute,
  GuideGuideColorRoute: GuideGuideColorRoute,
  GuideGuideInfoRoute: GuideGuideInfoRoute,
  GuideGuideRespondRoute: GuideGuideRespondRoute,
  GuideGuideTypographyRoute: GuideGuideTypographyRoute,
  GuideGuideIndexRoute: GuideGuideIndexRoute,
  GuideGuideComponentsLayoutRoute: GuideGuideComponentsLayoutRoute,
  GuideGuideComponentsLuttonRoute: GuideGuideComponentsLuttonRoute,
};

const GuideRouteWithChildren = GuideRoute._addFileChildren(GuideRouteChildren);

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute;
  LayoutMenu4Menu5Route: typeof LayoutMenu4Menu5Route;
  LayoutMenu8Menu9Route: typeof LayoutMenu8Menu9Route;
  LayoutMenu3IndexRoute: typeof LayoutMenu3IndexRoute;
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutMenu4Menu5Route: LayoutMenu4Menu5Route,
  LayoutMenu8Menu9Route: LayoutMenu8Menu9Route,
  LayoutMenu3IndexRoute: LayoutMenu3IndexRoute,
};

const LayoutRouteWithChildren = LayoutRoute._addFileChildren(LayoutRouteChildren);

interface LoginRouteChildren {
  LoginLayoutRoute: typeof LoginLayoutRoute;
  LoginIndexRoute: typeof LoginIndexRoute;
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginLayoutRoute: LoginLayoutRoute,
  LoginIndexRoute: LoginIndexRoute,
};

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren);

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren;
  '/login': typeof LoginLayoutRoute;
  '/': typeof LayoutIndexRoute;
  '/login/': typeof LoginIndexRoute;
  '/guide/button': typeof GuideGuideButtonRoute;
  '/guide/color': typeof GuideGuideColorRoute;
  '/guide/info': typeof GuideGuideInfoRoute;
  '/guide/respond': typeof GuideGuideRespondRoute;
  '/guide/typography': typeof GuideGuideTypographyRoute;
  '/menu4/menu5': typeof LayoutMenu4Menu5Route;
  '/menu8/menu9': typeof LayoutMenu8Menu9Route;
  '/guide': typeof GuideGuideIndexRoute;
  '/menu3': typeof LayoutMenu3IndexRoute;
  '/guide/components/Layout': typeof GuideGuideComponentsLayoutRoute;
  '/guide/components/Lutton': typeof GuideGuideComponentsLuttonRoute;
}

export interface FileRoutesByTo {
  '': typeof GuideRouteWithChildren;
  '/login': typeof LoginIndexRoute;
  '/': typeof LayoutIndexRoute;
  '/guide/button': typeof GuideGuideButtonRoute;
  '/guide/color': typeof GuideGuideColorRoute;
  '/guide/info': typeof GuideGuideInfoRoute;
  '/guide/respond': typeof GuideGuideRespondRoute;
  '/guide/typography': typeof GuideGuideTypographyRoute;
  '/menu4/menu5': typeof LayoutMenu4Menu5Route;
  '/menu8/menu9': typeof LayoutMenu8Menu9Route;
  '/guide': typeof GuideGuideIndexRoute;
  '/menu3': typeof LayoutMenu3IndexRoute;
  '/guide/components/Layout': typeof GuideGuideComponentsLayoutRoute;
  '/guide/components/Lutton': typeof GuideGuideComponentsLuttonRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/_guide': typeof GuideRouteWithChildren;
  '/_layout': typeof LayoutRouteWithChildren;
  '/login': typeof LoginRouteWithChildren;
  '/login/_layout': typeof LoginLayoutRoute;
  '/_layout/': typeof LayoutIndexRoute;
  '/login/': typeof LoginIndexRoute;
  '/_guide/guide/button': typeof GuideGuideButtonRoute;
  '/_guide/guide/color': typeof GuideGuideColorRoute;
  '/_guide/guide/info': typeof GuideGuideInfoRoute;
  '/_guide/guide/respond': typeof GuideGuideRespondRoute;
  '/_guide/guide/typography': typeof GuideGuideTypographyRoute;
  '/_layout/menu4/menu5': typeof LayoutMenu4Menu5Route;
  '/_layout/menu8/menu9': typeof LayoutMenu8Menu9Route;
  '/_guide/guide/': typeof GuideGuideIndexRoute;
  '/_layout/menu3/': typeof LayoutMenu3IndexRoute;
  '/_guide/guide/components/Layout': typeof GuideGuideComponentsLayoutRoute;
  '/_guide/guide/components/Lutton': typeof GuideGuideComponentsLuttonRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | ''
    | '/login'
    | '/'
    | '/login/'
    | '/guide/button'
    | '/guide/color'
    | '/guide/info'
    | '/guide/respond'
    | '/guide/typography'
    | '/menu4/menu5'
    | '/menu8/menu9'
    | '/guide'
    | '/menu3'
    | '/guide/components/Layout'
    | '/guide/components/Lutton';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | ''
    | '/login'
    | '/'
    | '/guide/button'
    | '/guide/color'
    | '/guide/info'
    | '/guide/respond'
    | '/guide/typography'
    | '/menu4/menu5'
    | '/menu8/menu9'
    | '/guide'
    | '/menu3'
    | '/guide/components/Layout'
    | '/guide/components/Lutton';
  id:
    | '__root__'
    | '/_guide'
    | '/_layout'
    | '/login'
    | '/login/_layout'
    | '/_layout/'
    | '/login/'
    | '/_guide/guide/button'
    | '/_guide/guide/color'
    | '/_guide/guide/info'
    | '/_guide/guide/respond'
    | '/_guide/guide/typography'
    | '/_layout/menu4/menu5'
    | '/_layout/menu8/menu9'
    | '/_guide/guide/'
    | '/_layout/menu3/'
    | '/_guide/guide/components/Layout'
    | '/_guide/guide/components/Lutton';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  GuideRoute: typeof GuideRouteWithChildren;
  LayoutRoute: typeof LayoutRouteWithChildren;
  LoginRoute: typeof LoginRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  GuideRoute: GuideRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_guide",
        "/_layout",
        "/login"
      ]
    },
    "/_guide": {
      "filePath": "_guide.tsx",
      "children": [
        "/_guide/guide/button",
        "/_guide/guide/color",
        "/_guide/guide/info",
        "/_guide/guide/respond",
        "/_guide/guide/typography",
        "/_guide/guide/",
        "/_guide/guide/components/Layout",
        "/_guide/guide/components/Lutton"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/menu4/menu5",
        "/_layout/menu8/menu9",
        "/_layout/menu3/"
      ]
    },
    "/login": {
      "filePath": "login",
      "children": [
        "/login/_layout",
        "/login/"
      ]
    },
    "/login/_layout": {
      "filePath": "login/_layout.tsx",
      "parent": "/login"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/login/": {
      "filePath": "login/index.tsx",
      "parent": "/login"
    },
    "/_guide/guide/button": {
      "filePath": "_guide/guide/button.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/color": {
      "filePath": "_guide/guide/color.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/info": {
      "filePath": "_guide/guide/info.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/respond": {
      "filePath": "_guide/guide/respond.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/typography": {
      "filePath": "_guide/guide/typography.tsx",
      "parent": "/_guide"
    },
    "/_layout/menu4/menu5": {
      "filePath": "_layout/menu4/menu5.tsx",
      "parent": "/_layout"
    },
    "/_layout/menu8/menu9": {
      "filePath": "_layout/menu8/menu9.tsx",
      "parent": "/_layout"
    },
    "/_guide/guide/": {
      "filePath": "_guide/guide/index.tsx",
      "parent": "/_guide"
    },
    "/_layout/menu3/": {
      "filePath": "_layout/menu3/index.tsx",
      "parent": "/_layout"
    },
    "/_guide/guide/components/Layout": {
      "filePath": "_guide/guide/components/Layout.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/components/Lutton": {
      "filePath": "_guide/guide/components/Lutton.tsx",
      "parent": "/_guide"
    }
  }
}
ROUTE_MANIFEST_END */
