/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as LayoutImport } from './pages/_layout'
import { Route as GuideImport } from './pages/_guide'
import { Route as AuthImport } from './pages/_auth'
import { Route as LayoutIndexImport } from './pages/_layout/index'
import { Route as LayoutTestImport } from './pages/_layout/test'
import { Route as LayoutMenuIdImport } from './pages/_layout/$menuId'
import { Route as AuthSuccessImport } from './pages/_auth/success'
import { Route as AuthSignupStep3Import } from './pages/_auth/signup-step3'
import { Route as AuthSignupStep2Import } from './pages/_auth/signup-step2'
import { Route as AuthSignupStep1Import } from './pages/_auth/signup-step1'
import { Route as AuthSearchIdSuccessImport } from './pages/_auth/search-id-success'
import { Route as AuthSearchAccountPwImport } from './pages/_auth/search-account-pw'
import { Route as AuthSearchAccountImport } from './pages/_auth/search-account'
import { Route as AuthProgressStatusCpImport } from './pages/_auth/progress-status-cp'
import { Route as AuthProgressStatusCertifyImport } from './pages/_auth/progress-status-certify'
import { Route as AuthProgressStatusAdminFailImport } from './pages/_auth/progress-status-admin-fail'
import { Route as AuthProgressStatusAdminImport } from './pages/_auth/progress-status-admin'
import { Route as AuthProgressStatusImport } from './pages/_auth/progress-status'
import { Route as AuthPasswordChangeImport } from './pages/_auth/password-change'
import { Route as AuthMpassCertImport } from './pages/_auth/mpass-cert'
import { Route as AuthLoginImport } from './pages/_auth/login'
import { Route as LayoutMenu3IndexImport } from './pages/_layout/menu3/index'
import { Route as GuideGuideIndexImport } from './pages/_guide/guide/index'
import { Route as LayoutPmsMenuManageImport } from './pages/_layout/pms/menuManage'
import { Route as LayoutMenu8Menu9Import } from './pages/_layout/menu8/menu9'
import { Route as LayoutMenu4Menu5Import } from './pages/_layout/menu4/menu5'
import { Route as LayoutLearningPopupUploadImport } from './pages/_layout/learning/popup-upload'
import { Route as LayoutLearningPopupLearningRegisterationImport } from './pages/_layout/learning/popup-learningRegisteration'
import { Route as LayoutLearningMediaRegisterImport } from './pages/_layout/learning/mediaRegister'
import { Route as LayoutLearningMediaDetailImport } from './pages/_layout/learning/mediaDetail'
import { Route as LayoutLearningLearningSearchImport } from './pages/_layout/learning/learningSearch'
import { Route as GuideGuideTypographyImport } from './pages/_guide/guide/typography'
import { Route as GuideGuideTooltipImport } from './pages/_guide/guide/tooltip'
import { Route as GuideGuideTestImport } from './pages/_guide/guide/test'
import { Route as GuideGuideTabsImport } from './pages/_guide/guide/tabs'
import { Route as GuideGuideSwitchImport } from './pages/_guide/guide/switch'
import { Route as GuideGuideStepperImport } from './pages/_guide/guide/stepper'
import { Route as GuideGuideSpinnerImport } from './pages/_guide/guide/spinner'
import { Route as GuideGuideSelectImport } from './pages/_guide/guide/select'
import { Route as GuideGuideRespondImport } from './pages/_guide/guide/respond'
import { Route as GuideGuideRadioImport } from './pages/_guide/guide/radio'
import { Route as GuideGuideProgressImport } from './pages/_guide/guide/progress'
import { Route as GuideGuidePanelImport } from './pages/_guide/guide/panel'
import { Route as GuideGuidePaginationImport } from './pages/_guide/guide/pagination'
import { Route as GuideGuideOptionCardImport } from './pages/_guide/guide/optionCard'
import { Route as GuideGuideModalImport } from './pages/_guide/guide/modal'
import { Route as GuideGuideLayoutImport } from './pages/_guide/guide/layout'
import { Route as GuideGuideInfoImport } from './pages/_guide/guide/info'
import { Route as GuideGuideIconImport } from './pages/_guide/guide/icon'
import { Route as GuideGuideGridImport } from './pages/_guide/guide/grid'
import { Route as GuideGuideFormImport } from './pages/_guide/guide/form'
import { Route as GuideGuideFileUploadImport } from './pages/_guide/guide/fileUpload'
import { Route as GuideGuideEmptyImport } from './pages/_guide/guide/empty'
import { Route as GuideGuideCssImport } from './pages/_guide/guide/css'
import { Route as GuideGuideColorImport } from './pages/_guide/guide/color'
import { Route as GuideGuideChipsImport } from './pages/_guide/guide/chips'
import { Route as GuideGuideCheckboxImport } from './pages/_guide/guide/checkbox'
import { Route as GuideGuideCarouselImport } from './pages/_guide/guide/carousel'
import { Route as GuideGuideButtonsImport } from './pages/_guide/guide/buttons'
import { Route as GuideGuideBadgeImport } from './pages/_guide/guide/badge'
import { Route as GuideGuideAlertImport } from './pages/_guide/guide/alert'
import { Route as GuideGuideAccordionImport } from './pages/_guide/guide/accordion'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const GuideRoute = GuideImport.update({
  id: '/_guide',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTestRoute = LayoutTestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMenuIdRoute = LayoutMenuIdImport.update({
  id: '/$menuId',
  path: '/$menuId',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthSuccessRoute = AuthSuccessImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSignupStep3Route = AuthSignupStep3Import.update({
  id: '/signup-step3',
  path: '/signup-step3',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSignupStep2Route = AuthSignupStep2Import.update({
  id: '/signup-step2',
  path: '/signup-step2',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSignupStep1Route = AuthSignupStep1Import.update({
  id: '/signup-step1',
  path: '/signup-step1',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSearchIdSuccessRoute = AuthSearchIdSuccessImport.update({
  id: '/search-id-success',
  path: '/search-id-success',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSearchAccountPwRoute = AuthSearchAccountPwImport.update({
  id: '/search-account-pw',
  path: '/search-account-pw',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSearchAccountRoute = AuthSearchAccountImport.update({
  id: '/search-account',
  path: '/search-account',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProgressStatusCpRoute = AuthProgressStatusCpImport.update({
  id: '/progress-status-cp',
  path: '/progress-status-cp',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProgressStatusCertifyRoute = AuthProgressStatusCertifyImport.update({
  id: '/progress-status-certify',
  path: '/progress-status-certify',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProgressStatusAdminFailRoute =
  AuthProgressStatusAdminFailImport.update({
    id: '/progress-status-admin-fail',
    path: '/progress-status-admin-fail',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthProgressStatusAdminRoute = AuthProgressStatusAdminImport.update({
  id: '/progress-status-admin',
  path: '/progress-status-admin',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProgressStatusRoute = AuthProgressStatusImport.update({
  id: '/progress-status',
  path: '/progress-status',
  getParentRoute: () => AuthRoute,
} as any)

const AuthPasswordChangeRoute = AuthPasswordChangeImport.update({
  id: '/password-change',
  path: '/password-change',
  getParentRoute: () => AuthRoute,
} as any)

const AuthMpassCertRoute = AuthMpassCertImport.update({
  id: '/mpass-cert',
  path: '/mpass-cert',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const LayoutMenu3IndexRoute = LayoutMenu3IndexImport.update({
  id: '/menu3/',
  path: '/menu3/',
  getParentRoute: () => LayoutRoute,
} as any)

const GuideGuideIndexRoute = GuideGuideIndexImport.update({
  id: '/guide/',
  path: '/guide/',
  getParentRoute: () => GuideRoute,
} as any)

const LayoutPmsMenuManageRoute = LayoutPmsMenuManageImport.update({
  id: '/pms/menuManage',
  path: '/pms/menuManage',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMenu8Menu9Route = LayoutMenu8Menu9Import.update({
  id: '/menu8/menu9',
  path: '/menu8/menu9',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMenu4Menu5Route = LayoutMenu4Menu5Import.update({
  id: '/menu4/menu5',
  path: '/menu4/menu5',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLearningPopupUploadRoute = LayoutLearningPopupUploadImport.update({
  id: '/learning/popup-upload',
  path: '/learning/popup-upload',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLearningPopupLearningRegisterationRoute =
  LayoutLearningPopupLearningRegisterationImport.update({
    id: '/learning/popup-learningRegisteration',
    path: '/learning/popup-learningRegisteration',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutLearningMediaRegisterRoute =
  LayoutLearningMediaRegisterImport.update({
    id: '/learning/mediaRegister',
    path: '/learning/mediaRegister',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutLearningMediaDetailRoute = LayoutLearningMediaDetailImport.update({
  id: '/learning/mediaDetail',
  path: '/learning/mediaDetail',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLearningLearningSearchRoute =
  LayoutLearningLearningSearchImport.update({
    id: '/learning/learningSearch',
    path: '/learning/learningSearch',
    getParentRoute: () => LayoutRoute,
  } as any)

const GuideGuideTypographyRoute = GuideGuideTypographyImport.update({
  id: '/guide/typography',
  path: '/guide/typography',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideTooltipRoute = GuideGuideTooltipImport.update({
  id: '/guide/tooltip',
  path: '/guide/tooltip',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideTestRoute = GuideGuideTestImport.update({
  id: '/guide/test',
  path: '/guide/test',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideTabsRoute = GuideGuideTabsImport.update({
  id: '/guide/tabs',
  path: '/guide/tabs',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideSwitchRoute = GuideGuideSwitchImport.update({
  id: '/guide/switch',
  path: '/guide/switch',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideStepperRoute = GuideGuideStepperImport.update({
  id: '/guide/stepper',
  path: '/guide/stepper',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideSpinnerRoute = GuideGuideSpinnerImport.update({
  id: '/guide/spinner',
  path: '/guide/spinner',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideSelectRoute = GuideGuideSelectImport.update({
  id: '/guide/select',
  path: '/guide/select',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideRespondRoute = GuideGuideRespondImport.update({
  id: '/guide/respond',
  path: '/guide/respond',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideRadioRoute = GuideGuideRadioImport.update({
  id: '/guide/radio',
  path: '/guide/radio',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideProgressRoute = GuideGuideProgressImport.update({
  id: '/guide/progress',
  path: '/guide/progress',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuidePanelRoute = GuideGuidePanelImport.update({
  id: '/guide/panel',
  path: '/guide/panel',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuidePaginationRoute = GuideGuidePaginationImport.update({
  id: '/guide/pagination',
  path: '/guide/pagination',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideOptionCardRoute = GuideGuideOptionCardImport.update({
  id: '/guide/optionCard',
  path: '/guide/optionCard',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideModalRoute = GuideGuideModalImport.update({
  id: '/guide/modal',
  path: '/guide/modal',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideLayoutRoute = GuideGuideLayoutImport.update({
  id: '/guide/layout',
  path: '/guide/layout',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideInfoRoute = GuideGuideInfoImport.update({
  id: '/guide/info',
  path: '/guide/info',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideIconRoute = GuideGuideIconImport.update({
  id: '/guide/icon',
  path: '/guide/icon',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideGridRoute = GuideGuideGridImport.update({
  id: '/guide/grid',
  path: '/guide/grid',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideFormRoute = GuideGuideFormImport.update({
  id: '/guide/form',
  path: '/guide/form',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideFileUploadRoute = GuideGuideFileUploadImport.update({
  id: '/guide/fileUpload',
  path: '/guide/fileUpload',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideEmptyRoute = GuideGuideEmptyImport.update({
  id: '/guide/empty',
  path: '/guide/empty',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideCssRoute = GuideGuideCssImport.update({
  id: '/guide/css',
  path: '/guide/css',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideColorRoute = GuideGuideColorImport.update({
  id: '/guide/color',
  path: '/guide/color',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideChipsRoute = GuideGuideChipsImport.update({
  id: '/guide/chips',
  path: '/guide/chips',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideCheckboxRoute = GuideGuideCheckboxImport.update({
  id: '/guide/checkbox',
  path: '/guide/checkbox',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideCarouselRoute = GuideGuideCarouselImport.update({
  id: '/guide/carousel',
  path: '/guide/carousel',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideButtonsRoute = GuideGuideButtonsImport.update({
  id: '/guide/buttons',
  path: '/guide/buttons',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideBadgeRoute = GuideGuideBadgeImport.update({
  id: '/guide/badge',
  path: '/guide/badge',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideAlertRoute = GuideGuideAlertImport.update({
  id: '/guide/alert',
  path: '/guide/alert',
  getParentRoute: () => GuideRoute,
} as any)

const GuideGuideAccordionRoute = GuideGuideAccordionImport.update({
  id: '/guide/accordion',
  path: '/guide/accordion',
  getParentRoute: () => GuideRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_guide': {
      id: '/_guide'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuideImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/mpass-cert': {
      id: '/_auth/mpass-cert'
      path: '/mpass-cert'
      fullPath: '/mpass-cert'
      preLoaderRoute: typeof AuthMpassCertImport
      parentRoute: typeof AuthImport
    }
    '/_auth/password-change': {
      id: '/_auth/password-change'
      path: '/password-change'
      fullPath: '/password-change'
      preLoaderRoute: typeof AuthPasswordChangeImport
      parentRoute: typeof AuthImport
    }
    '/_auth/progress-status': {
      id: '/_auth/progress-status'
      path: '/progress-status'
      fullPath: '/progress-status'
      preLoaderRoute: typeof AuthProgressStatusImport
      parentRoute: typeof AuthImport
    }
    '/_auth/progress-status-admin': {
      id: '/_auth/progress-status-admin'
      path: '/progress-status-admin'
      fullPath: '/progress-status-admin'
      preLoaderRoute: typeof AuthProgressStatusAdminImport
      parentRoute: typeof AuthImport
    }
    '/_auth/progress-status-admin-fail': {
      id: '/_auth/progress-status-admin-fail'
      path: '/progress-status-admin-fail'
      fullPath: '/progress-status-admin-fail'
      preLoaderRoute: typeof AuthProgressStatusAdminFailImport
      parentRoute: typeof AuthImport
    }
    '/_auth/progress-status-certify': {
      id: '/_auth/progress-status-certify'
      path: '/progress-status-certify'
      fullPath: '/progress-status-certify'
      preLoaderRoute: typeof AuthProgressStatusCertifyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/progress-status-cp': {
      id: '/_auth/progress-status-cp'
      path: '/progress-status-cp'
      fullPath: '/progress-status-cp'
      preLoaderRoute: typeof AuthProgressStatusCpImport
      parentRoute: typeof AuthImport
    }
    '/_auth/search-account': {
      id: '/_auth/search-account'
      path: '/search-account'
      fullPath: '/search-account'
      preLoaderRoute: typeof AuthSearchAccountImport
      parentRoute: typeof AuthImport
    }
    '/_auth/search-account-pw': {
      id: '/_auth/search-account-pw'
      path: '/search-account-pw'
      fullPath: '/search-account-pw'
      preLoaderRoute: typeof AuthSearchAccountPwImport
      parentRoute: typeof AuthImport
    }
    '/_auth/search-id-success': {
      id: '/_auth/search-id-success'
      path: '/search-id-success'
      fullPath: '/search-id-success'
      preLoaderRoute: typeof AuthSearchIdSuccessImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup-step1': {
      id: '/_auth/signup-step1'
      path: '/signup-step1'
      fullPath: '/signup-step1'
      preLoaderRoute: typeof AuthSignupStep1Import
      parentRoute: typeof AuthImport
    }
    '/_auth/signup-step2': {
      id: '/_auth/signup-step2'
      path: '/signup-step2'
      fullPath: '/signup-step2'
      preLoaderRoute: typeof AuthSignupStep2Import
      parentRoute: typeof AuthImport
    }
    '/_auth/signup-step3': {
      id: '/_auth/signup-step3'
      path: '/signup-step3'
      fullPath: '/signup-step3'
      preLoaderRoute: typeof AuthSignupStep3Import
      parentRoute: typeof AuthImport
    }
    '/_auth/success': {
      id: '/_auth/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof AuthSuccessImport
      parentRoute: typeof AuthImport
    }
    '/_layout/$menuId': {
      id: '/_layout/$menuId'
      path: '/$menuId'
      fullPath: '/$menuId'
      preLoaderRoute: typeof LayoutMenuIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/test': {
      id: '/_layout/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof LayoutTestImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_guide/guide/accordion': {
      id: '/_guide/guide/accordion'
      path: '/guide/accordion'
      fullPath: '/guide/accordion'
      preLoaderRoute: typeof GuideGuideAccordionImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/alert': {
      id: '/_guide/guide/alert'
      path: '/guide/alert'
      fullPath: '/guide/alert'
      preLoaderRoute: typeof GuideGuideAlertImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/badge': {
      id: '/_guide/guide/badge'
      path: '/guide/badge'
      fullPath: '/guide/badge'
      preLoaderRoute: typeof GuideGuideBadgeImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/buttons': {
      id: '/_guide/guide/buttons'
      path: '/guide/buttons'
      fullPath: '/guide/buttons'
      preLoaderRoute: typeof GuideGuideButtonsImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/carousel': {
      id: '/_guide/guide/carousel'
      path: '/guide/carousel'
      fullPath: '/guide/carousel'
      preLoaderRoute: typeof GuideGuideCarouselImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/checkbox': {
      id: '/_guide/guide/checkbox'
      path: '/guide/checkbox'
      fullPath: '/guide/checkbox'
      preLoaderRoute: typeof GuideGuideCheckboxImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/chips': {
      id: '/_guide/guide/chips'
      path: '/guide/chips'
      fullPath: '/guide/chips'
      preLoaderRoute: typeof GuideGuideChipsImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/color': {
      id: '/_guide/guide/color'
      path: '/guide/color'
      fullPath: '/guide/color'
      preLoaderRoute: typeof GuideGuideColorImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/css': {
      id: '/_guide/guide/css'
      path: '/guide/css'
      fullPath: '/guide/css'
      preLoaderRoute: typeof GuideGuideCssImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/empty': {
      id: '/_guide/guide/empty'
      path: '/guide/empty'
      fullPath: '/guide/empty'
      preLoaderRoute: typeof GuideGuideEmptyImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/fileUpload': {
      id: '/_guide/guide/fileUpload'
      path: '/guide/fileUpload'
      fullPath: '/guide/fileUpload'
      preLoaderRoute: typeof GuideGuideFileUploadImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/form': {
      id: '/_guide/guide/form'
      path: '/guide/form'
      fullPath: '/guide/form'
      preLoaderRoute: typeof GuideGuideFormImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/grid': {
      id: '/_guide/guide/grid'
      path: '/guide/grid'
      fullPath: '/guide/grid'
      preLoaderRoute: typeof GuideGuideGridImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/icon': {
      id: '/_guide/guide/icon'
      path: '/guide/icon'
      fullPath: '/guide/icon'
      preLoaderRoute: typeof GuideGuideIconImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/info': {
      id: '/_guide/guide/info'
      path: '/guide/info'
      fullPath: '/guide/info'
      preLoaderRoute: typeof GuideGuideInfoImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/layout': {
      id: '/_guide/guide/layout'
      path: '/guide/layout'
      fullPath: '/guide/layout'
      preLoaderRoute: typeof GuideGuideLayoutImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/modal': {
      id: '/_guide/guide/modal'
      path: '/guide/modal'
      fullPath: '/guide/modal'
      preLoaderRoute: typeof GuideGuideModalImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/optionCard': {
      id: '/_guide/guide/optionCard'
      path: '/guide/optionCard'
      fullPath: '/guide/optionCard'
      preLoaderRoute: typeof GuideGuideOptionCardImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/pagination': {
      id: '/_guide/guide/pagination'
      path: '/guide/pagination'
      fullPath: '/guide/pagination'
      preLoaderRoute: typeof GuideGuidePaginationImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/panel': {
      id: '/_guide/guide/panel'
      path: '/guide/panel'
      fullPath: '/guide/panel'
      preLoaderRoute: typeof GuideGuidePanelImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/progress': {
      id: '/_guide/guide/progress'
      path: '/guide/progress'
      fullPath: '/guide/progress'
      preLoaderRoute: typeof GuideGuideProgressImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/radio': {
      id: '/_guide/guide/radio'
      path: '/guide/radio'
      fullPath: '/guide/radio'
      preLoaderRoute: typeof GuideGuideRadioImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/respond': {
      id: '/_guide/guide/respond'
      path: '/guide/respond'
      fullPath: '/guide/respond'
      preLoaderRoute: typeof GuideGuideRespondImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/select': {
      id: '/_guide/guide/select'
      path: '/guide/select'
      fullPath: '/guide/select'
      preLoaderRoute: typeof GuideGuideSelectImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/spinner': {
      id: '/_guide/guide/spinner'
      path: '/guide/spinner'
      fullPath: '/guide/spinner'
      preLoaderRoute: typeof GuideGuideSpinnerImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/stepper': {
      id: '/_guide/guide/stepper'
      path: '/guide/stepper'
      fullPath: '/guide/stepper'
      preLoaderRoute: typeof GuideGuideStepperImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/switch': {
      id: '/_guide/guide/switch'
      path: '/guide/switch'
      fullPath: '/guide/switch'
      preLoaderRoute: typeof GuideGuideSwitchImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/tabs': {
      id: '/_guide/guide/tabs'
      path: '/guide/tabs'
      fullPath: '/guide/tabs'
      preLoaderRoute: typeof GuideGuideTabsImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/test': {
      id: '/_guide/guide/test'
      path: '/guide/test'
      fullPath: '/guide/test'
      preLoaderRoute: typeof GuideGuideTestImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/tooltip': {
      id: '/_guide/guide/tooltip'
      path: '/guide/tooltip'
      fullPath: '/guide/tooltip'
      preLoaderRoute: typeof GuideGuideTooltipImport
      parentRoute: typeof GuideImport
    }
    '/_guide/guide/typography': {
      id: '/_guide/guide/typography'
      path: '/guide/typography'
      fullPath: '/guide/typography'
      preLoaderRoute: typeof GuideGuideTypographyImport
      parentRoute: typeof GuideImport
    }
    '/_layout/learning/learningSearch': {
      id: '/_layout/learning/learningSearch'
      path: '/learning/learningSearch'
      fullPath: '/learning/learningSearch'
      preLoaderRoute: typeof LayoutLearningLearningSearchImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/learning/mediaDetail': {
      id: '/_layout/learning/mediaDetail'
      path: '/learning/mediaDetail'
      fullPath: '/learning/mediaDetail'
      preLoaderRoute: typeof LayoutLearningMediaDetailImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/learning/mediaRegister': {
      id: '/_layout/learning/mediaRegister'
      path: '/learning/mediaRegister'
      fullPath: '/learning/mediaRegister'
      preLoaderRoute: typeof LayoutLearningMediaRegisterImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/learning/popup-learningRegisteration': {
      id: '/_layout/learning/popup-learningRegisteration'
      path: '/learning/popup-learningRegisteration'
      fullPath: '/learning/popup-learningRegisteration'
      preLoaderRoute: typeof LayoutLearningPopupLearningRegisterationImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/learning/popup-upload': {
      id: '/_layout/learning/popup-upload'
      path: '/learning/popup-upload'
      fullPath: '/learning/popup-upload'
      preLoaderRoute: typeof LayoutLearningPopupUploadImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/menu4/menu5': {
      id: '/_layout/menu4/menu5'
      path: '/menu4/menu5'
      fullPath: '/menu4/menu5'
      preLoaderRoute: typeof LayoutMenu4Menu5Import
      parentRoute: typeof LayoutImport
    }
    '/_layout/menu8/menu9': {
      id: '/_layout/menu8/menu9'
      path: '/menu8/menu9'
      fullPath: '/menu8/menu9'
      preLoaderRoute: typeof LayoutMenu8Menu9Import
      parentRoute: typeof LayoutImport
    }
    '/_layout/pms/menuManage': {
      id: '/_layout/pms/menuManage'
      path: '/pms/menuManage'
      fullPath: '/pms/menuManage'
      preLoaderRoute: typeof LayoutPmsMenuManageImport
      parentRoute: typeof LayoutImport
    }
    '/_guide/guide/': {
      id: '/_guide/guide/'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideGuideIndexImport
      parentRoute: typeof GuideImport
    }
    '/_layout/menu3/': {
      id: '/_layout/menu3/'
      path: '/menu3'
      fullPath: '/menu3'
      preLoaderRoute: typeof LayoutMenu3IndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMpassCertRoute: typeof AuthMpassCertRoute
  AuthPasswordChangeRoute: typeof AuthPasswordChangeRoute
  AuthProgressStatusRoute: typeof AuthProgressStatusRoute
  AuthProgressStatusAdminRoute: typeof AuthProgressStatusAdminRoute
  AuthProgressStatusAdminFailRoute: typeof AuthProgressStatusAdminFailRoute
  AuthProgressStatusCertifyRoute: typeof AuthProgressStatusCertifyRoute
  AuthProgressStatusCpRoute: typeof AuthProgressStatusCpRoute
  AuthSearchAccountRoute: typeof AuthSearchAccountRoute
  AuthSearchAccountPwRoute: typeof AuthSearchAccountPwRoute
  AuthSearchIdSuccessRoute: typeof AuthSearchIdSuccessRoute
  AuthSignupStep1Route: typeof AuthSignupStep1Route
  AuthSignupStep2Route: typeof AuthSignupStep2Route
  AuthSignupStep3Route: typeof AuthSignupStep3Route
  AuthSuccessRoute: typeof AuthSuccessRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthMpassCertRoute: AuthMpassCertRoute,
  AuthPasswordChangeRoute: AuthPasswordChangeRoute,
  AuthProgressStatusRoute: AuthProgressStatusRoute,
  AuthProgressStatusAdminRoute: AuthProgressStatusAdminRoute,
  AuthProgressStatusAdminFailRoute: AuthProgressStatusAdminFailRoute,
  AuthProgressStatusCertifyRoute: AuthProgressStatusCertifyRoute,
  AuthProgressStatusCpRoute: AuthProgressStatusCpRoute,
  AuthSearchAccountRoute: AuthSearchAccountRoute,
  AuthSearchAccountPwRoute: AuthSearchAccountPwRoute,
  AuthSearchIdSuccessRoute: AuthSearchIdSuccessRoute,
  AuthSignupStep1Route: AuthSignupStep1Route,
  AuthSignupStep2Route: AuthSignupStep2Route,
  AuthSignupStep3Route: AuthSignupStep3Route,
  AuthSuccessRoute: AuthSuccessRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuideRouteChildren {
  GuideGuideAccordionRoute: typeof GuideGuideAccordionRoute
  GuideGuideAlertRoute: typeof GuideGuideAlertRoute
  GuideGuideBadgeRoute: typeof GuideGuideBadgeRoute
  GuideGuideButtonsRoute: typeof GuideGuideButtonsRoute
  GuideGuideCarouselRoute: typeof GuideGuideCarouselRoute
  GuideGuideCheckboxRoute: typeof GuideGuideCheckboxRoute
  GuideGuideChipsRoute: typeof GuideGuideChipsRoute
  GuideGuideColorRoute: typeof GuideGuideColorRoute
  GuideGuideCssRoute: typeof GuideGuideCssRoute
  GuideGuideEmptyRoute: typeof GuideGuideEmptyRoute
  GuideGuideFileUploadRoute: typeof GuideGuideFileUploadRoute
  GuideGuideFormRoute: typeof GuideGuideFormRoute
  GuideGuideGridRoute: typeof GuideGuideGridRoute
  GuideGuideIconRoute: typeof GuideGuideIconRoute
  GuideGuideInfoRoute: typeof GuideGuideInfoRoute
  GuideGuideLayoutRoute: typeof GuideGuideLayoutRoute
  GuideGuideModalRoute: typeof GuideGuideModalRoute
  GuideGuideOptionCardRoute: typeof GuideGuideOptionCardRoute
  GuideGuidePaginationRoute: typeof GuideGuidePaginationRoute
  GuideGuidePanelRoute: typeof GuideGuidePanelRoute
  GuideGuideProgressRoute: typeof GuideGuideProgressRoute
  GuideGuideRadioRoute: typeof GuideGuideRadioRoute
  GuideGuideRespondRoute: typeof GuideGuideRespondRoute
  GuideGuideSelectRoute: typeof GuideGuideSelectRoute
  GuideGuideSpinnerRoute: typeof GuideGuideSpinnerRoute
  GuideGuideStepperRoute: typeof GuideGuideStepperRoute
  GuideGuideSwitchRoute: typeof GuideGuideSwitchRoute
  GuideGuideTabsRoute: typeof GuideGuideTabsRoute
  GuideGuideTestRoute: typeof GuideGuideTestRoute
  GuideGuideTooltipRoute: typeof GuideGuideTooltipRoute
  GuideGuideTypographyRoute: typeof GuideGuideTypographyRoute
  GuideGuideIndexRoute: typeof GuideGuideIndexRoute
}

const GuideRouteChildren: GuideRouteChildren = {
  GuideGuideAccordionRoute: GuideGuideAccordionRoute,
  GuideGuideAlertRoute: GuideGuideAlertRoute,
  GuideGuideBadgeRoute: GuideGuideBadgeRoute,
  GuideGuideButtonsRoute: GuideGuideButtonsRoute,
  GuideGuideCarouselRoute: GuideGuideCarouselRoute,
  GuideGuideCheckboxRoute: GuideGuideCheckboxRoute,
  GuideGuideChipsRoute: GuideGuideChipsRoute,
  GuideGuideColorRoute: GuideGuideColorRoute,
  GuideGuideCssRoute: GuideGuideCssRoute,
  GuideGuideEmptyRoute: GuideGuideEmptyRoute,
  GuideGuideFileUploadRoute: GuideGuideFileUploadRoute,
  GuideGuideFormRoute: GuideGuideFormRoute,
  GuideGuideGridRoute: GuideGuideGridRoute,
  GuideGuideIconRoute: GuideGuideIconRoute,
  GuideGuideInfoRoute: GuideGuideInfoRoute,
  GuideGuideLayoutRoute: GuideGuideLayoutRoute,
  GuideGuideModalRoute: GuideGuideModalRoute,
  GuideGuideOptionCardRoute: GuideGuideOptionCardRoute,
  GuideGuidePaginationRoute: GuideGuidePaginationRoute,
  GuideGuidePanelRoute: GuideGuidePanelRoute,
  GuideGuideProgressRoute: GuideGuideProgressRoute,
  GuideGuideRadioRoute: GuideGuideRadioRoute,
  GuideGuideRespondRoute: GuideGuideRespondRoute,
  GuideGuideSelectRoute: GuideGuideSelectRoute,
  GuideGuideSpinnerRoute: GuideGuideSpinnerRoute,
  GuideGuideStepperRoute: GuideGuideStepperRoute,
  GuideGuideSwitchRoute: GuideGuideSwitchRoute,
  GuideGuideTabsRoute: GuideGuideTabsRoute,
  GuideGuideTestRoute: GuideGuideTestRoute,
  GuideGuideTooltipRoute: GuideGuideTooltipRoute,
  GuideGuideTypographyRoute: GuideGuideTypographyRoute,
  GuideGuideIndexRoute: GuideGuideIndexRoute,
}

const GuideRouteWithChildren = GuideRoute._addFileChildren(GuideRouteChildren)

interface LayoutRouteChildren {
  LayoutMenuIdRoute: typeof LayoutMenuIdRoute
  LayoutTestRoute: typeof LayoutTestRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutLearningLearningSearchRoute: typeof LayoutLearningLearningSearchRoute
  LayoutLearningMediaDetailRoute: typeof LayoutLearningMediaDetailRoute
  LayoutLearningMediaRegisterRoute: typeof LayoutLearningMediaRegisterRoute
  LayoutLearningPopupLearningRegisterationRoute: typeof LayoutLearningPopupLearningRegisterationRoute
  LayoutLearningPopupUploadRoute: typeof LayoutLearningPopupUploadRoute
  LayoutMenu4Menu5Route: typeof LayoutMenu4Menu5Route
  LayoutMenu8Menu9Route: typeof LayoutMenu8Menu9Route
  LayoutPmsMenuManageRoute: typeof LayoutPmsMenuManageRoute
  LayoutMenu3IndexRoute: typeof LayoutMenu3IndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutMenuIdRoute: LayoutMenuIdRoute,
  LayoutTestRoute: LayoutTestRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutLearningLearningSearchRoute: LayoutLearningLearningSearchRoute,
  LayoutLearningMediaDetailRoute: LayoutLearningMediaDetailRoute,
  LayoutLearningMediaRegisterRoute: LayoutLearningMediaRegisterRoute,
  LayoutLearningPopupLearningRegisterationRoute:
    LayoutLearningPopupLearningRegisterationRoute,
  LayoutLearningPopupUploadRoute: LayoutLearningPopupUploadRoute,
  LayoutMenu4Menu5Route: LayoutMenu4Menu5Route,
  LayoutMenu8Menu9Route: LayoutMenu8Menu9Route,
  LayoutPmsMenuManageRoute: LayoutPmsMenuManageRoute,
  LayoutMenu3IndexRoute: LayoutMenu3IndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/mpass-cert': typeof AuthMpassCertRoute
  '/password-change': typeof AuthPasswordChangeRoute
  '/progress-status': typeof AuthProgressStatusRoute
  '/progress-status-admin': typeof AuthProgressStatusAdminRoute
  '/progress-status-admin-fail': typeof AuthProgressStatusAdminFailRoute
  '/progress-status-certify': typeof AuthProgressStatusCertifyRoute
  '/progress-status-cp': typeof AuthProgressStatusCpRoute
  '/search-account': typeof AuthSearchAccountRoute
  '/search-account-pw': typeof AuthSearchAccountPwRoute
  '/search-id-success': typeof AuthSearchIdSuccessRoute
  '/signup-step1': typeof AuthSignupStep1Route
  '/signup-step2': typeof AuthSignupStep2Route
  '/signup-step3': typeof AuthSignupStep3Route
  '/success': typeof AuthSuccessRoute
  '/$menuId': typeof LayoutMenuIdRoute
  '/test': typeof LayoutTestRoute
  '/': typeof LayoutIndexRoute
  '/guide/accordion': typeof GuideGuideAccordionRoute
  '/guide/alert': typeof GuideGuideAlertRoute
  '/guide/badge': typeof GuideGuideBadgeRoute
  '/guide/buttons': typeof GuideGuideButtonsRoute
  '/guide/carousel': typeof GuideGuideCarouselRoute
  '/guide/checkbox': typeof GuideGuideCheckboxRoute
  '/guide/chips': typeof GuideGuideChipsRoute
  '/guide/color': typeof GuideGuideColorRoute
  '/guide/css': typeof GuideGuideCssRoute
  '/guide/empty': typeof GuideGuideEmptyRoute
  '/guide/fileUpload': typeof GuideGuideFileUploadRoute
  '/guide/form': typeof GuideGuideFormRoute
  '/guide/grid': typeof GuideGuideGridRoute
  '/guide/icon': typeof GuideGuideIconRoute
  '/guide/info': typeof GuideGuideInfoRoute
  '/guide/layout': typeof GuideGuideLayoutRoute
  '/guide/modal': typeof GuideGuideModalRoute
  '/guide/optionCard': typeof GuideGuideOptionCardRoute
  '/guide/pagination': typeof GuideGuidePaginationRoute
  '/guide/panel': typeof GuideGuidePanelRoute
  '/guide/progress': typeof GuideGuideProgressRoute
  '/guide/radio': typeof GuideGuideRadioRoute
  '/guide/respond': typeof GuideGuideRespondRoute
  '/guide/select': typeof GuideGuideSelectRoute
  '/guide/spinner': typeof GuideGuideSpinnerRoute
  '/guide/stepper': typeof GuideGuideStepperRoute
  '/guide/switch': typeof GuideGuideSwitchRoute
  '/guide/tabs': typeof GuideGuideTabsRoute
  '/guide/test': typeof GuideGuideTestRoute
  '/guide/tooltip': typeof GuideGuideTooltipRoute
  '/guide/typography': typeof GuideGuideTypographyRoute
  '/learning/learningSearch': typeof LayoutLearningLearningSearchRoute
  '/learning/mediaDetail': typeof LayoutLearningMediaDetailRoute
  '/learning/mediaRegister': typeof LayoutLearningMediaRegisterRoute
  '/learning/popup-learningRegisteration': typeof LayoutLearningPopupLearningRegisterationRoute
  '/learning/popup-upload': typeof LayoutLearningPopupUploadRoute
  '/menu4/menu5': typeof LayoutMenu4Menu5Route
  '/menu8/menu9': typeof LayoutMenu8Menu9Route
  '/pms/menuManage': typeof LayoutPmsMenuManageRoute
  '/guide': typeof GuideGuideIndexRoute
  '/menu3': typeof LayoutMenu3IndexRoute
}

export interface FileRoutesByTo {
  '': typeof GuideRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/mpass-cert': typeof AuthMpassCertRoute
  '/password-change': typeof AuthPasswordChangeRoute
  '/progress-status': typeof AuthProgressStatusRoute
  '/progress-status-admin': typeof AuthProgressStatusAdminRoute
  '/progress-status-admin-fail': typeof AuthProgressStatusAdminFailRoute
  '/progress-status-certify': typeof AuthProgressStatusCertifyRoute
  '/progress-status-cp': typeof AuthProgressStatusCpRoute
  '/search-account': typeof AuthSearchAccountRoute
  '/search-account-pw': typeof AuthSearchAccountPwRoute
  '/search-id-success': typeof AuthSearchIdSuccessRoute
  '/signup-step1': typeof AuthSignupStep1Route
  '/signup-step2': typeof AuthSignupStep2Route
  '/signup-step3': typeof AuthSignupStep3Route
  '/success': typeof AuthSuccessRoute
  '/$menuId': typeof LayoutMenuIdRoute
  '/test': typeof LayoutTestRoute
  '/': typeof LayoutIndexRoute
  '/guide/accordion': typeof GuideGuideAccordionRoute
  '/guide/alert': typeof GuideGuideAlertRoute
  '/guide/badge': typeof GuideGuideBadgeRoute
  '/guide/buttons': typeof GuideGuideButtonsRoute
  '/guide/carousel': typeof GuideGuideCarouselRoute
  '/guide/checkbox': typeof GuideGuideCheckboxRoute
  '/guide/chips': typeof GuideGuideChipsRoute
  '/guide/color': typeof GuideGuideColorRoute
  '/guide/css': typeof GuideGuideCssRoute
  '/guide/empty': typeof GuideGuideEmptyRoute
  '/guide/fileUpload': typeof GuideGuideFileUploadRoute
  '/guide/form': typeof GuideGuideFormRoute
  '/guide/grid': typeof GuideGuideGridRoute
  '/guide/icon': typeof GuideGuideIconRoute
  '/guide/info': typeof GuideGuideInfoRoute
  '/guide/layout': typeof GuideGuideLayoutRoute
  '/guide/modal': typeof GuideGuideModalRoute
  '/guide/optionCard': typeof GuideGuideOptionCardRoute
  '/guide/pagination': typeof GuideGuidePaginationRoute
  '/guide/panel': typeof GuideGuidePanelRoute
  '/guide/progress': typeof GuideGuideProgressRoute
  '/guide/radio': typeof GuideGuideRadioRoute
  '/guide/respond': typeof GuideGuideRespondRoute
  '/guide/select': typeof GuideGuideSelectRoute
  '/guide/spinner': typeof GuideGuideSpinnerRoute
  '/guide/stepper': typeof GuideGuideStepperRoute
  '/guide/switch': typeof GuideGuideSwitchRoute
  '/guide/tabs': typeof GuideGuideTabsRoute
  '/guide/test': typeof GuideGuideTestRoute
  '/guide/tooltip': typeof GuideGuideTooltipRoute
  '/guide/typography': typeof GuideGuideTypographyRoute
  '/learning/learningSearch': typeof LayoutLearningLearningSearchRoute
  '/learning/mediaDetail': typeof LayoutLearningMediaDetailRoute
  '/learning/mediaRegister': typeof LayoutLearningMediaRegisterRoute
  '/learning/popup-learningRegisteration': typeof LayoutLearningPopupLearningRegisterationRoute
  '/learning/popup-upload': typeof LayoutLearningPopupUploadRoute
  '/menu4/menu5': typeof LayoutMenu4Menu5Route
  '/menu8/menu9': typeof LayoutMenu8Menu9Route
  '/pms/menuManage': typeof LayoutPmsMenuManageRoute
  '/guide': typeof GuideGuideIndexRoute
  '/menu3': typeof LayoutMenu3IndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guide': typeof GuideRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/mpass-cert': typeof AuthMpassCertRoute
  '/_auth/password-change': typeof AuthPasswordChangeRoute
  '/_auth/progress-status': typeof AuthProgressStatusRoute
  '/_auth/progress-status-admin': typeof AuthProgressStatusAdminRoute
  '/_auth/progress-status-admin-fail': typeof AuthProgressStatusAdminFailRoute
  '/_auth/progress-status-certify': typeof AuthProgressStatusCertifyRoute
  '/_auth/progress-status-cp': typeof AuthProgressStatusCpRoute
  '/_auth/search-account': typeof AuthSearchAccountRoute
  '/_auth/search-account-pw': typeof AuthSearchAccountPwRoute
  '/_auth/search-id-success': typeof AuthSearchIdSuccessRoute
  '/_auth/signup-step1': typeof AuthSignupStep1Route
  '/_auth/signup-step2': typeof AuthSignupStep2Route
  '/_auth/signup-step3': typeof AuthSignupStep3Route
  '/_auth/success': typeof AuthSuccessRoute
  '/_layout/$menuId': typeof LayoutMenuIdRoute
  '/_layout/test': typeof LayoutTestRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_guide/guide/accordion': typeof GuideGuideAccordionRoute
  '/_guide/guide/alert': typeof GuideGuideAlertRoute
  '/_guide/guide/badge': typeof GuideGuideBadgeRoute
  '/_guide/guide/buttons': typeof GuideGuideButtonsRoute
  '/_guide/guide/carousel': typeof GuideGuideCarouselRoute
  '/_guide/guide/checkbox': typeof GuideGuideCheckboxRoute
  '/_guide/guide/chips': typeof GuideGuideChipsRoute
  '/_guide/guide/color': typeof GuideGuideColorRoute
  '/_guide/guide/css': typeof GuideGuideCssRoute
  '/_guide/guide/empty': typeof GuideGuideEmptyRoute
  '/_guide/guide/fileUpload': typeof GuideGuideFileUploadRoute
  '/_guide/guide/form': typeof GuideGuideFormRoute
  '/_guide/guide/grid': typeof GuideGuideGridRoute
  '/_guide/guide/icon': typeof GuideGuideIconRoute
  '/_guide/guide/info': typeof GuideGuideInfoRoute
  '/_guide/guide/layout': typeof GuideGuideLayoutRoute
  '/_guide/guide/modal': typeof GuideGuideModalRoute
  '/_guide/guide/optionCard': typeof GuideGuideOptionCardRoute
  '/_guide/guide/pagination': typeof GuideGuidePaginationRoute
  '/_guide/guide/panel': typeof GuideGuidePanelRoute
  '/_guide/guide/progress': typeof GuideGuideProgressRoute
  '/_guide/guide/radio': typeof GuideGuideRadioRoute
  '/_guide/guide/respond': typeof GuideGuideRespondRoute
  '/_guide/guide/select': typeof GuideGuideSelectRoute
  '/_guide/guide/spinner': typeof GuideGuideSpinnerRoute
  '/_guide/guide/stepper': typeof GuideGuideStepperRoute
  '/_guide/guide/switch': typeof GuideGuideSwitchRoute
  '/_guide/guide/tabs': typeof GuideGuideTabsRoute
  '/_guide/guide/test': typeof GuideGuideTestRoute
  '/_guide/guide/tooltip': typeof GuideGuideTooltipRoute
  '/_guide/guide/typography': typeof GuideGuideTypographyRoute
  '/_layout/learning/learningSearch': typeof LayoutLearningLearningSearchRoute
  '/_layout/learning/mediaDetail': typeof LayoutLearningMediaDetailRoute
  '/_layout/learning/mediaRegister': typeof LayoutLearningMediaRegisterRoute
  '/_layout/learning/popup-learningRegisteration': typeof LayoutLearningPopupLearningRegisterationRoute
  '/_layout/learning/popup-upload': typeof LayoutLearningPopupUploadRoute
  '/_layout/menu4/menu5': typeof LayoutMenu4Menu5Route
  '/_layout/menu8/menu9': typeof LayoutMenu8Menu9Route
  '/_layout/pms/menuManage': typeof LayoutPmsMenuManageRoute
  '/_guide/guide/': typeof GuideGuideIndexRoute
  '/_layout/menu3/': typeof LayoutMenu3IndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/mpass-cert'
    | '/password-change'
    | '/progress-status'
    | '/progress-status-admin'
    | '/progress-status-admin-fail'
    | '/progress-status-certify'
    | '/progress-status-cp'
    | '/search-account'
    | '/search-account-pw'
    | '/search-id-success'
    | '/signup-step1'
    | '/signup-step2'
    | '/signup-step3'
    | '/success'
    | '/$menuId'
    | '/test'
    | '/'
    | '/guide/accordion'
    | '/guide/alert'
    | '/guide/badge'
    | '/guide/buttons'
    | '/guide/carousel'
    | '/guide/checkbox'
    | '/guide/chips'
    | '/guide/color'
    | '/guide/css'
    | '/guide/empty'
    | '/guide/fileUpload'
    | '/guide/form'
    | '/guide/grid'
    | '/guide/icon'
    | '/guide/info'
    | '/guide/layout'
    | '/guide/modal'
    | '/guide/optionCard'
    | '/guide/pagination'
    | '/guide/panel'
    | '/guide/progress'
    | '/guide/radio'
    | '/guide/respond'
    | '/guide/select'
    | '/guide/spinner'
    | '/guide/stepper'
    | '/guide/switch'
    | '/guide/tabs'
    | '/guide/test'
    | '/guide/tooltip'
    | '/guide/typography'
    | '/learning/learningSearch'
    | '/learning/mediaDetail'
    | '/learning/mediaRegister'
    | '/learning/popup-learningRegisteration'
    | '/learning/popup-upload'
    | '/menu4/menu5'
    | '/menu8/menu9'
    | '/pms/menuManage'
    | '/guide'
    | '/menu3'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/mpass-cert'
    | '/password-change'
    | '/progress-status'
    | '/progress-status-admin'
    | '/progress-status-admin-fail'
    | '/progress-status-certify'
    | '/progress-status-cp'
    | '/search-account'
    | '/search-account-pw'
    | '/search-id-success'
    | '/signup-step1'
    | '/signup-step2'
    | '/signup-step3'
    | '/success'
    | '/$menuId'
    | '/test'
    | '/'
    | '/guide/accordion'
    | '/guide/alert'
    | '/guide/badge'
    | '/guide/buttons'
    | '/guide/carousel'
    | '/guide/checkbox'
    | '/guide/chips'
    | '/guide/color'
    | '/guide/css'
    | '/guide/empty'
    | '/guide/fileUpload'
    | '/guide/form'
    | '/guide/grid'
    | '/guide/icon'
    | '/guide/info'
    | '/guide/layout'
    | '/guide/modal'
    | '/guide/optionCard'
    | '/guide/pagination'
    | '/guide/panel'
    | '/guide/progress'
    | '/guide/radio'
    | '/guide/respond'
    | '/guide/select'
    | '/guide/spinner'
    | '/guide/stepper'
    | '/guide/switch'
    | '/guide/tabs'
    | '/guide/test'
    | '/guide/tooltip'
    | '/guide/typography'
    | '/learning/learningSearch'
    | '/learning/mediaDetail'
    | '/learning/mediaRegister'
    | '/learning/popup-learningRegisteration'
    | '/learning/popup-upload'
    | '/menu4/menu5'
    | '/menu8/menu9'
    | '/pms/menuManage'
    | '/guide'
    | '/menu3'
  id:
    | '__root__'
    | '/_auth'
    | '/_guide'
    | '/_layout'
    | '/_auth/login'
    | '/_auth/mpass-cert'
    | '/_auth/password-change'
    | '/_auth/progress-status'
    | '/_auth/progress-status-admin'
    | '/_auth/progress-status-admin-fail'
    | '/_auth/progress-status-certify'
    | '/_auth/progress-status-cp'
    | '/_auth/search-account'
    | '/_auth/search-account-pw'
    | '/_auth/search-id-success'
    | '/_auth/signup-step1'
    | '/_auth/signup-step2'
    | '/_auth/signup-step3'
    | '/_auth/success'
    | '/_layout/$menuId'
    | '/_layout/test'
    | '/_layout/'
    | '/_guide/guide/accordion'
    | '/_guide/guide/alert'
    | '/_guide/guide/badge'
    | '/_guide/guide/buttons'
    | '/_guide/guide/carousel'
    | '/_guide/guide/checkbox'
    | '/_guide/guide/chips'
    | '/_guide/guide/color'
    | '/_guide/guide/css'
    | '/_guide/guide/empty'
    | '/_guide/guide/fileUpload'
    | '/_guide/guide/form'
    | '/_guide/guide/grid'
    | '/_guide/guide/icon'
    | '/_guide/guide/info'
    | '/_guide/guide/layout'
    | '/_guide/guide/modal'
    | '/_guide/guide/optionCard'
    | '/_guide/guide/pagination'
    | '/_guide/guide/panel'
    | '/_guide/guide/progress'
    | '/_guide/guide/radio'
    | '/_guide/guide/respond'
    | '/_guide/guide/select'
    | '/_guide/guide/spinner'
    | '/_guide/guide/stepper'
    | '/_guide/guide/switch'
    | '/_guide/guide/tabs'
    | '/_guide/guide/test'
    | '/_guide/guide/tooltip'
    | '/_guide/guide/typography'
    | '/_layout/learning/learningSearch'
    | '/_layout/learning/mediaDetail'
    | '/_layout/learning/mediaRegister'
    | '/_layout/learning/popup-learningRegisteration'
    | '/_layout/learning/popup-upload'
    | '/_layout/menu4/menu5'
    | '/_layout/menu8/menu9'
    | '/_layout/pms/menuManage'
    | '/_guide/guide/'
    | '/_layout/menu3/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  GuideRoute: typeof GuideRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  GuideRoute: GuideRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_guide",
        "/_layout"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login",
        "/_auth/mpass-cert",
        "/_auth/password-change",
        "/_auth/progress-status",
        "/_auth/progress-status-admin",
        "/_auth/progress-status-admin-fail",
        "/_auth/progress-status-certify",
        "/_auth/progress-status-cp",
        "/_auth/search-account",
        "/_auth/search-account-pw",
        "/_auth/search-id-success",
        "/_auth/signup-step1",
        "/_auth/signup-step2",
        "/_auth/signup-step3",
        "/_auth/success"
      ]
    },
    "/_guide": {
      "filePath": "_guide.tsx",
      "children": [
        "/_guide/guide/accordion",
        "/_guide/guide/alert",
        "/_guide/guide/badge",
        "/_guide/guide/buttons",
        "/_guide/guide/carousel",
        "/_guide/guide/checkbox",
        "/_guide/guide/chips",
        "/_guide/guide/color",
        "/_guide/guide/css",
        "/_guide/guide/empty",
        "/_guide/guide/fileUpload",
        "/_guide/guide/form",
        "/_guide/guide/grid",
        "/_guide/guide/icon",
        "/_guide/guide/info",
        "/_guide/guide/layout",
        "/_guide/guide/modal",
        "/_guide/guide/optionCard",
        "/_guide/guide/pagination",
        "/_guide/guide/panel",
        "/_guide/guide/progress",
        "/_guide/guide/radio",
        "/_guide/guide/respond",
        "/_guide/guide/select",
        "/_guide/guide/spinner",
        "/_guide/guide/stepper",
        "/_guide/guide/switch",
        "/_guide/guide/tabs",
        "/_guide/guide/test",
        "/_guide/guide/tooltip",
        "/_guide/guide/typography",
        "/_guide/guide/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/$menuId",
        "/_layout/test",
        "/_layout/",
        "/_layout/learning/learningSearch",
        "/_layout/learning/mediaDetail",
        "/_layout/learning/mediaRegister",
        "/_layout/learning/popup-learningRegisteration",
        "/_layout/learning/popup-upload",
        "/_layout/menu4/menu5",
        "/_layout/menu8/menu9",
        "/_layout/pms/menuManage",
        "/_layout/menu3/"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/mpass-cert": {
      "filePath": "_auth/mpass-cert.tsx",
      "parent": "/_auth"
    },
    "/_auth/password-change": {
      "filePath": "_auth/password-change.tsx",
      "parent": "/_auth"
    },
    "/_auth/progress-status": {
      "filePath": "_auth/progress-status.tsx",
      "parent": "/_auth"
    },
    "/_auth/progress-status-admin": {
      "filePath": "_auth/progress-status-admin.tsx",
      "parent": "/_auth"
    },
    "/_auth/progress-status-admin-fail": {
      "filePath": "_auth/progress-status-admin-fail.tsx",
      "parent": "/_auth"
    },
    "/_auth/progress-status-certify": {
      "filePath": "_auth/progress-status-certify.tsx",
      "parent": "/_auth"
    },
    "/_auth/progress-status-cp": {
      "filePath": "_auth/progress-status-cp.tsx",
      "parent": "/_auth"
    },
    "/_auth/search-account": {
      "filePath": "_auth/search-account.tsx",
      "parent": "/_auth"
    },
    "/_auth/search-account-pw": {
      "filePath": "_auth/search-account-pw.tsx",
      "parent": "/_auth"
    },
    "/_auth/search-id-success": {
      "filePath": "_auth/search-id-success.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup-step1": {
      "filePath": "_auth/signup-step1.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup-step2": {
      "filePath": "_auth/signup-step2.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup-step3": {
      "filePath": "_auth/signup-step3.tsx",
      "parent": "/_auth"
    },
    "/_auth/success": {
      "filePath": "_auth/success.tsx",
      "parent": "/_auth"
    },
    "/_layout/$menuId": {
      "filePath": "_layout/$menuId.tsx",
      "parent": "/_layout"
    },
    "/_layout/test": {
      "filePath": "_layout/test.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_guide/guide/accordion": {
      "filePath": "_guide/guide/accordion.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/alert": {
      "filePath": "_guide/guide/alert.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/badge": {
      "filePath": "_guide/guide/badge.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/buttons": {
      "filePath": "_guide/guide/buttons.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/carousel": {
      "filePath": "_guide/guide/carousel.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/checkbox": {
      "filePath": "_guide/guide/checkbox.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/chips": {
      "filePath": "_guide/guide/chips.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/color": {
      "filePath": "_guide/guide/color.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/css": {
      "filePath": "_guide/guide/css.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/empty": {
      "filePath": "_guide/guide/empty.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/fileUpload": {
      "filePath": "_guide/guide/fileUpload.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/form": {
      "filePath": "_guide/guide/form.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/grid": {
      "filePath": "_guide/guide/grid.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/icon": {
      "filePath": "_guide/guide/icon.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/info": {
      "filePath": "_guide/guide/info.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/layout": {
      "filePath": "_guide/guide/layout.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/modal": {
      "filePath": "_guide/guide/modal.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/optionCard": {
      "filePath": "_guide/guide/optionCard.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/pagination": {
      "filePath": "_guide/guide/pagination.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/panel": {
      "filePath": "_guide/guide/panel.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/progress": {
      "filePath": "_guide/guide/progress.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/radio": {
      "filePath": "_guide/guide/radio.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/respond": {
      "filePath": "_guide/guide/respond.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/select": {
      "filePath": "_guide/guide/select.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/spinner": {
      "filePath": "_guide/guide/spinner.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/stepper": {
      "filePath": "_guide/guide/stepper.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/switch": {
      "filePath": "_guide/guide/switch.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/tabs": {
      "filePath": "_guide/guide/tabs.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/test": {
      "filePath": "_guide/guide/test.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/tooltip": {
      "filePath": "_guide/guide/tooltip.tsx",
      "parent": "/_guide"
    },
    "/_guide/guide/typography": {
      "filePath": "_guide/guide/typography.tsx",
      "parent": "/_guide"
    },
    "/_layout/learning/learningSearch": {
      "filePath": "_layout/learning/learningSearch.tsx",
      "parent": "/_layout"
    },
    "/_layout/learning/mediaDetail": {
      "filePath": "_layout/learning/mediaDetail.tsx",
      "parent": "/_layout"
    },
    "/_layout/learning/mediaRegister": {
      "filePath": "_layout/learning/mediaRegister.tsx",
      "parent": "/_layout"
    },
    "/_layout/learning/popup-learningRegisteration": {
      "filePath": "_layout/learning/popup-learningRegisteration.tsx",
      "parent": "/_layout"
    },
    "/_layout/learning/popup-upload": {
      "filePath": "_layout/learning/popup-upload.tsx",
      "parent": "/_layout"
    },
    "/_layout/menu4/menu5": {
      "filePath": "_layout/menu4/menu5.tsx",
      "parent": "/_layout"
    },
    "/_layout/menu8/menu9": {
      "filePath": "_layout/menu8/menu9.tsx",
      "parent": "/_layout"
    },
    "/_layout/pms/menuManage": {
      "filePath": "_layout/pms/menuManage.tsx",
      "parent": "/_layout"
    },
    "/_guide/guide/": {
      "filePath": "_guide/guide/index.tsx",
      "parent": "/_guide"
    },
    "/_layout/menu3/": {
      "filePath": "_layout/menu3/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
