export const SESSION_TIMEOUT_LIMIT_DURATION = 1000 * 60 * 60 * 2; // 2시간 = 1000 * 60 * 60 * 2 = 7200000
export const SESSION_TIMEOUT_EXTENSION_ALERT_DURATION = 1000 * 60 * 5; // 경과 5분전 = 1000 * 60 * 5 = 300000

// NLP_BO_LOG_1000 / 로그인 / 로그인 > 로그인 > 관리자 로그인 얼럿
export const AUTH_ERROR_CODE = {
  NOTFOUND_ID: '',
  PASSWORD_FAIL: '',
  LOGIN_LOCK_PASSWORD_USE: '',
  LOGIN_LOCK_PASSWORD_NOT_USE: '',
  APPROVAL_ADMIN_PENDING: '',
  APPROVAL_ADMIN_REJECT: '',
  APPROVAL_CP_PENDING: '',
  APPROVAL_CP_REJECT: '',
  PASSWORD_CHANGE_PASSWORD_USE: '',
  PASSWORD_CHANGE_PASSWORD_NOT_USE: '',
  TENANT_PENDING: '',
};
