export enum EnLibGlobalConst {
  SYSTEM_COMMON_CODE = 'SYSTEM_COMMON_CODE',
  LEARNER_MENU = 'LEARNER_MENU',
  HRD_CENTER_MENU = 'HRD_CENTER_MENU',
}

export enum CourseType {
  ELEARNING1 = 'ELEARNING1',
  ELEARNING2 = 'ELEARNING2',
  CLASS = 'CLASS',
  LIVE = 'LIVE',
  EXAM = 'EXAM',
  SURVEY = 'SURVEY',
}
