export interface LearningSequences {
  openingYear: number;
  courseSequenceNo: number;
  courseSequenceId: number;
  courseSequenceName: string;
  learningStartType: string;
  enrollmentStartDateTime: string;
  enrollmentEndDateTime: string;
  courseSequenceStartDateTime: string;
  courseSequenceEndDateTime: string;
  learningStartDays: number;
  learningStatusType: string;
  isUsed: boolean;
  maxEnrollQuota: number;
  currentEnrollCount: number;
  enrolledStudentCount: number;
  graduatedStudentCount: number;
}

export interface LearningSequence {
  courseType: string;
  channelUuid: string;
  tenantList?: Array<number>;
  targetListIds?: Array<number>;
  targetList?: Array<any>;
  courseSequenceName: string;
  isUsed: boolean;
  enrollmentRange?: any;
  enrollStartDateTime?: string;
  enrollEndDateTime?: string;
  isEnrollCancelDeadLineActivated: boolean;
  enrollCancelRange?: any;
  enrollCancelStartDateTime?: string | null;
  enrollCancelEndDateTime?: string | null;
  learningStartType: string;
  learningStartDays?: number | null;
  learningStartRange?: any;
  learningStartDateTime?: string | null;
  learningEndDateTime?: string | null;
  learningSpaceType: string;
  learningSpaceId?: number | null;
  learningSpaceName?: string | null;
  learningSpaceNameKeyIn?: string | null;
  approvalLineType: string;
  isMaxEnrollQuotaRestricted: boolean;
  maxEnrollQuota: number;
  waitListPickMethodType: string;
  maxWaitlistQuota: number;
  isInstructorAssigned: boolean;
  instructorAssignType: string;
  instructorId?: number;
  instructorName?: string | null;
  isTextbookProvided: boolean;
  textbookName: string;
  textbookFee: number;
  coordinatorUuid: string;
  coordinatorName: string;
  coordinatorDeptName: string;
  coordinatorTelCountryCode: string;
  coordinatorTelNo: string;
  coordinatorEmail: string;
  operatorUuid: string;
  operatorName: string;
  operatorDeptName: string;
  operatorTelCountryCode: string;
  operatorTelNo: string;
  operatorEmail: string;
  isUsePassOption: boolean;
  passMethodType: string;
  isCertificateProvided: boolean;
  progressMinPassScore: number;
  attendanceMinPassScore: number;
  examMinPassScore: number;
  asgmtMinPassScore: number;
  totalMinPassScore: number;
  progressWeights: number;
  attendanceWeights: number;
  examWeights: number;
  asgmtWeights: number;
  recognizedStudyMinType: string;
  recognizedStudyCycles?: number | null;
  recognizedStudyMinutes?: number | null;
  isRecognizedStudyPoint: boolean;
  recognizedStudyPoint?: number | null;
  isLearnEnvEnabled: boolean;
  deviceRestrictType: string;
  isIntranetRestricted: boolean;
  learningRestrictTimeType: string;
  isReviewRestricted: boolean;
  maxReviewPeriodMonths?: number | null;
  isCaptureBlockEnabled: boolean;
  isSecurityAgreementEnable: boolean;
  isLearnControlEnabled: boolean;
  isDailyLearningProgressRestricted: boolean;
  maxDailyLearningProgress?: number | null;
  isProgressResetEnabled: boolean;
  isSequentialLearningRequired: boolean;
  isPlayerControlRestricted: boolean;
  maxPlayBackRate: string;
  hmgStandardMainCategory: string;
  hmgStandardSubCategory: string;
  isUseTrainingCostPerPerson: boolean;
  trainingCostPerPerson?: number | null;
  isUseEmploymentInsuranceRefund: boolean;
  employmentInsuranceRefund?: number | null;
  isStayed: boolean;
  isCarTenantCustomOption: boolean;
  isRotemTenantCustomOption: boolean;
  isOutsourcingTenantCustomOption: boolean;
  isWiaTenantCustomOption: boolean;
  isAutoeverTenantCustomOption: boolean;
  tenantCustoms: Array<any>;
  curriculumId?: number;
}

export interface LearningSequenceCombo {
  courseSequenceId: number;
  courseSequenceName: string;
}
