/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as LayoutImport } from './pages/_layout'
import { Route as LoginIndexImport } from './pages/login/index'
import { Route as LayoutIndexImport } from './pages/_layout/index'
import { Route as LayoutMenu3IndexImport } from './pages/_layout/menu3/index'
import { Route as LayoutMenuIndexImport } from './pages/_layout/menu/index'
import { Route as LayoutMenu8Menu9Import } from './pages/_layout/menu8/menu9'
import { Route as LayoutMenu6Menu7Import } from './pages/_layout/menu6/menu7'
import { Route as LayoutMenu4Menu5Import } from './pages/_layout/menu4/menu5'
import { Route as LayoutMenuMenuIdImport } from './pages/_layout/menu/$menuId'
import { Route as LayoutCategoryCategoryIdImport } from './pages/_layout/category/$categoryId'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMenu3IndexRoute = LayoutMenu3IndexImport.update({
  id: '/menu3/',
  path: '/menu3/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMenuIndexRoute = LayoutMenuIndexImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMenu8Menu9Route = LayoutMenu8Menu9Import.update({
  id: '/menu8/menu9',
  path: '/menu8/menu9',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMenu6Menu7Route = LayoutMenu6Menu7Import.update({
  id: '/menu6/menu7',
  path: '/menu6/menu7',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMenu4Menu5Route = LayoutMenu4Menu5Import.update({
  id: '/menu4/menu5',
  path: '/menu4/menu5',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMenuMenuIdRoute = LayoutMenuMenuIdImport.update({
  id: '/menu/$menuId',
  path: '/menu/$menuId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCategoryCategoryIdRoute = LayoutCategoryCategoryIdImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout/category/$categoryId': {
      id: '/_layout/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof LayoutCategoryCategoryIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/menu/$menuId': {
      id: '/_layout/menu/$menuId'
      path: '/menu/$menuId'
      fullPath: '/menu/$menuId'
      preLoaderRoute: typeof LayoutMenuMenuIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/menu4/menu5': {
      id: '/_layout/menu4/menu5'
      path: '/menu4/menu5'
      fullPath: '/menu4/menu5'
      preLoaderRoute: typeof LayoutMenu4Menu5Import
      parentRoute: typeof LayoutImport
    }
    '/_layout/menu6/menu7': {
      id: '/_layout/menu6/menu7'
      path: '/menu6/menu7'
      fullPath: '/menu6/menu7'
      preLoaderRoute: typeof LayoutMenu6Menu7Import
      parentRoute: typeof LayoutImport
    }
    '/_layout/menu8/menu9': {
      id: '/_layout/menu8/menu9'
      path: '/menu8/menu9'
      fullPath: '/menu8/menu9'
      preLoaderRoute: typeof LayoutMenu8Menu9Import
      parentRoute: typeof LayoutImport
    }
    '/_layout/menu/': {
      id: '/_layout/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof LayoutMenuIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/menu3/': {
      id: '/_layout/menu3/'
      path: '/menu3'
      fullPath: '/menu3'
      preLoaderRoute: typeof LayoutMenu3IndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCategoryCategoryIdRoute: typeof LayoutCategoryCategoryIdRoute
  LayoutMenuMenuIdRoute: typeof LayoutMenuMenuIdRoute
  LayoutMenu4Menu5Route: typeof LayoutMenu4Menu5Route
  LayoutMenu6Menu7Route: typeof LayoutMenu6Menu7Route
  LayoutMenu8Menu9Route: typeof LayoutMenu8Menu9Route
  LayoutMenuIndexRoute: typeof LayoutMenuIndexRoute
  LayoutMenu3IndexRoute: typeof LayoutMenu3IndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCategoryCategoryIdRoute: LayoutCategoryCategoryIdRoute,
  LayoutMenuMenuIdRoute: LayoutMenuMenuIdRoute,
  LayoutMenu4Menu5Route: LayoutMenu4Menu5Route,
  LayoutMenu6Menu7Route: LayoutMenu6Menu7Route,
  LayoutMenu8Menu9Route: LayoutMenu8Menu9Route,
  LayoutMenuIndexRoute: LayoutMenuIndexRoute,
  LayoutMenu3IndexRoute: LayoutMenu3IndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/category/$categoryId': typeof LayoutCategoryCategoryIdRoute
  '/menu/$menuId': typeof LayoutMenuMenuIdRoute
  '/menu4/menu5': typeof LayoutMenu4Menu5Route
  '/menu6/menu7': typeof LayoutMenu6Menu7Route
  '/menu8/menu9': typeof LayoutMenu8Menu9Route
  '/menu': typeof LayoutMenuIndexRoute
  '/menu3': typeof LayoutMenu3IndexRoute
}

export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/category/$categoryId': typeof LayoutCategoryCategoryIdRoute
  '/menu/$menuId': typeof LayoutMenuMenuIdRoute
  '/menu4/menu5': typeof LayoutMenu4Menu5Route
  '/menu6/menu7': typeof LayoutMenu6Menu7Route
  '/menu8/menu9': typeof LayoutMenu8Menu9Route
  '/menu': typeof LayoutMenuIndexRoute
  '/menu3': typeof LayoutMenu3IndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_layout/category/$categoryId': typeof LayoutCategoryCategoryIdRoute
  '/_layout/menu/$menuId': typeof LayoutMenuMenuIdRoute
  '/_layout/menu4/menu5': typeof LayoutMenu4Menu5Route
  '/_layout/menu6/menu7': typeof LayoutMenu6Menu7Route
  '/_layout/menu8/menu9': typeof LayoutMenu8Menu9Route
  '/_layout/menu/': typeof LayoutMenuIndexRoute
  '/_layout/menu3/': typeof LayoutMenu3IndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/login'
    | '/category/$categoryId'
    | '/menu/$menuId'
    | '/menu4/menu5'
    | '/menu6/menu7'
    | '/menu8/menu9'
    | '/menu'
    | '/menu3'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/category/$categoryId'
    | '/menu/$menuId'
    | '/menu4/menu5'
    | '/menu6/menu7'
    | '/menu8/menu9'
    | '/menu'
    | '/menu3'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/login/'
    | '/_layout/category/$categoryId'
    | '/_layout/menu/$menuId'
    | '/_layout/menu4/menu5'
    | '/_layout/menu6/menu7'
    | '/_layout/menu8/menu9'
    | '/_layout/menu/'
    | '/_layout/menu3/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/login/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/category/$categoryId",
        "/_layout/menu/$menuId",
        "/_layout/menu4/menu5",
        "/_layout/menu6/menu7",
        "/_layout/menu8/menu9",
        "/_layout/menu/",
        "/_layout/menu3/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/_layout/category/$categoryId": {
      "filePath": "_layout/category/$categoryId.tsx",
      "parent": "/_layout"
    },
    "/_layout/menu/$menuId": {
      "filePath": "_layout/menu/$menuId.tsx",
      "parent": "/_layout"
    },
    "/_layout/menu4/menu5": {
      "filePath": "_layout/menu4/menu5.tsx",
      "parent": "/_layout"
    },
    "/_layout/menu6/menu7": {
      "filePath": "_layout/menu6/menu7.tsx",
      "parent": "/_layout"
    },
    "/_layout/menu8/menu9": {
      "filePath": "_layout/menu8/menu9.tsx",
      "parent": "/_layout"
    },
    "/_layout/menu/": {
      "filePath": "_layout/menu/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/menu3/": {
      "filePath": "_layout/menu3/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
